apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  {{- with .Values.service }}
  {{- if (or (eq .type "ClusterIP") (empty .type)) }}
  type: ClusterIP
  {{- else if eq .type "LoadBalancer" }}
  type: LoadBalancer
  {{- if .LoadBalancerIP }}
  LoadBalancerIP: {{ .LoadBalancerIP }}
  {{- end }}
  {{- if .externalTrafficPolicy }}
  externalTrafficPolicy: {{ .externalTrafficPolicy }}
  {{- end }}
  {{- end }}
  ports:
    - name: service
      port: {{ .port }}
      targetPort: {{ $.Values.port }}
  {{- end }}
  selector:
    app: {{ .Values.name }}
