apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configName }}
          env:
            - name: ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: AccessKeyId
            - name: SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: SecretAccessKey
                  #resources:
                  #      requests:
                  #memory: "256Mi"
                  # cpu: "1000m"
      dnsConfig:
        options:
          - name: ndots
            value: "1"
